version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_DATABASE: prm_project
      MYSQL_ROOT_PASSWORD: boot.ai
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build: .
    container_name: spring-app
    restart: always
    depends_on:
      - mysql
    ports:
      - "9080:9080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/prm_project?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: boot.ai
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

volumes:
  mysql_data:
